# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
#install:
  #- pip install -r requirements.txt
  #- pip install .
#command to run tests
script: python bofhbot.py --version
